    public enum CanvasType
    {
        IntroCanvas,
        CompletionCanvas,
        GameplayCanvas,
        PCScreenCanvas,
        ComputerHome,
        ComputerEmail,
        ComputerInbox,
        ComputerSchoolPage,
        ComputerStudentPortal,
        PhoneHome,
        PhoneMusicApp,
        PhoneWeatherApp,
        PhoneCallApp,
        PhoneMessagingApp,
        PhoneAuthenticatorApp,
        ComputerNotepad,
        GameOverCanvas,
        PhoneMFACheck,
        ComputerLogin
    }